on:
  push:
    branches:
    - main

jobs:
  generate_wiki:
    name: generate-wiki
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v6
      with:
        python-version: '3.13'
    - name: setup venv
      run: python -m venv venv; ./venv/bin/pip install -r requirements.txt
    
    - name: clone zr repo
      run: git clone https://github.com/artvin01/TF2-Zombie-Riot
    - run: ls
    - name: run main script
      run: ./venv/bin/python main.py
    
    # TODO: main script should move markdown into wiki by itself?
    - name: push to wiki
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git clone https://github.com/squarebracket-s/tf2_zr_wikigen.wiki.git
        mv weapons.md ./tf2_zr_wikigen.wiki/Weapons.md
        mv wavesets.md ./tf2_zr_wikigen.wiki/Wavesets.md
        cd tf2_zr_wikigen.wiki
        git add .
        git commit -m "Generate Wiki [$GITHUB_SHA]"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/squarebracket-s/tf2_zr_wikigen.wiki.git
        git push origin master
